core/urls.py
from django.urls import include, path
from . views import *

app_name = 'core'

urlpatterns = [

    path('', home, name='index'),
    path('ref/<str:ref_code>/<str:username>/', index, name='index'),
    path('referral', referral, name='referral'),

    #path('giftweb/', include('giftweb.urls', namespace='giftweb')),

]

giftweb/urls.py


# urls.py 

from django.urls import path
from .views import *

app_name = 'giftweb'

urlpatterns = [
    path('', home, name='home'),
    path('documents', documentHome, name='documents'),
    path('business', businessHome, name='business'),
    path('about/', about, name='about'),
    path('policy/', policy, name='policy'),
    path('contact/', contact, name='contact'),
    path('blogs/', blog_list, name='blog_list'),

    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('document/<int:pk>/', DocumentDetailView.as_view(), name='document_detail'),
    path('business/<int:pk>/', BusinessView.as_view(), name='business_detail'),
    path('make_payment/<str:model_name>/<int:product_id>/', make_payment, name='make_payment'),
    path('make_crypto_payment/<str:model_name>/<int:product_id>/', make_crypto_payment, name='make_crypto_payment'),


    path('payment_success/', payment_success, name='payment_success'),
    path('crypto_payment_success/', crypto_payment_success, name='crypto_payment_success'),
    path('products/category/<str:category_name>/', products_by_category, name='products_by_category'),
    path('documents/category/<str:category_name>/', documents_by_category, name='documents_by_category'),

    
    # Add the following URL for payment history
    path('payment_history/', payment_history, name='payment_history'),
]

portmark/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('giftweb.urls', namespace='giftweb')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('core/', include('core.urls', namespace='core')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )


giftweb/forms.py


#forms.py

from django import forms
from .models import *

from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from .models import CryptoPayment



class PaymentForm(forms.ModelForm):
    gift_card_type = forms.ChoiceField(choices=[('apple', 'Apple Card'), ('amazon', 'Amazon Card'), ('steam', 'Steam Card'), ('xbox', 'Xbox Card')])

    code = forms.CharField(
        label='username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter the Gift Card Code',
                'required': True,
            }
        )
    )
    country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    full_name = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Full Name',
                'required': True,
            }
        )
    )
    street_address = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Street Address',
                'required': True,
            }
        )
    )
    apartment_address = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Apartment Address',
                'required': True,
            }
        )
    )
    phone_number = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Phone No',
                'required': True,
            }
        )
    )
    quantity = forms.IntegerField(
        label='Quantity',
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'min': '1',
                'value': '1',
                'required': True,
            }
        )
    )

    class Meta:
        model = Payment
        fields = ['quantity', 'amount', 'proof_of_pay', 'gift_card_type', 'code', 'country', 'full_name', 'street_address', 'apartment_address', 'phone_number']


#forms.py

class CryptoPaymentForm(forms.ModelForm):



    country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    full_name = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Full Name',
                'required': True,
            }
        )
    )
    street_address = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Street Address',
                'required': True,
            }
        )
    )
    apartment_address = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Apartment Address',
                'required': True,
            }
        )
    )
    phone_number = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter your Phone No',
                'required': True,
            }
        )
    )
    quantity = forms.IntegerField(
        label='Quantity',
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'min': '1',
                'value': '1',
                'required': True,
            }
        )
    )
    class Meta:
        model = Payment


    class Meta:
        model = CryptoPayment
        fields = ['quantity','payment_method', 'amount', 'proof_of_pay', 'country', 'full_name', 'street_address', 'apartment_address', 'phone_number']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Make the amount field read-only
        self.fields['proof_of_pay'].widget.attrs['accept'] = 'image/*'
        


giftweb/views.py

#Grade 2

#views.py

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import *
from .forms import PaymentForm
from django.views.generic import DetailView
from datetime import timedelta
from django.core.paginator import Paginator
from django.contrib import messages
from accounts.models import Profile
from django.contrib.auth.decorators import login_required
from .forms import *


@login_required
def payment_history(request):
    # Fetch both regular payments and crypto payments for the user
    regular_payments = Payment.objects.filter(user=request.user)
    crypto_payments = CryptoPayment.objects.filter(user=request.user)
    
    # Combine the two querysets
    combined_payments = sorted(
        list(regular_payments) + list(crypto_payments),
        key=lambda x: x.date, 
        reverse=True
    )

    paginator = Paginator(combined_payments, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'giftweb/payment_history.html', {'page_obj': page_obj})

#views.py

@login_required
def make_crypto_payment(request, model_name, product_id):
    if model_name == 'product':
        model = Product
    elif model_name == 'premium_product':
        model = PremiumProduct
    else:
        return HttpResponseBadRequest("Invalid model name.")

    product = get_object_or_404(model, id=product_id)
    wallets_instance = CryptoCurrency.objects.first()

    if request.method == 'POST':
        form = CryptoPaymentForm(request.POST, request.FILES)  # Ensure the correct form class is used
        if form.is_valid():
            payment = form.save(commit=False)
            payment.product = product
            payment.status = 'PENDING'
            payment.user = request.user
            # Calculate total amount based on product price and quantity
            payment.amount = product.price * form.cleaned_data['quantity']
            payment.save()
            return redirect('giftweb:crypto_payment_success')
        else:
            print(form.errors)  # Print form errors to the console
    else:
        form = CryptoPaymentForm()

    return render(request, 'giftweb/crypto_checkout.html', {'form': form, 'wallets_instance': wallets_instance, 'product': product})


@login_required
def crypto_payment_success(request):
    payment = CryptoPayment.objects.filter(user=request.user).order_by('-id').first()
    return render(request, 'giftweb/crypto_payment_success.html', {'payment': payment})




@login_required
def make_payment(request, model_name, product_id):
    if model_name == 'product':
        model = Product
    elif model_name == 'premium_product':
        model = PremiumProduct
    else:
        return HttpResponseBadRequest("Invalid model name.")

    product = get_object_or_404(model, id=product_id)

    if request.method == 'POST':
        form = PaymentForm(request.POST, request.FILES)
        if form.is_valid():
            payment = form.save(commit=False)
            payment.product = product
            payment.status = 'PENDING'
            payment.user = request.user
            # Calculate total amount based on product price and quantity
            payment.amount = product.price * form.cleaned_data['quantity']
            payment.save()
            return redirect('giftweb:payment_success')
    else:
        form = PaymentForm()
    
    return render(request, 'giftweb/checkout.html', {'form': form, 'product': product})




def products_by_category(request, category_name):
    category = Category.objects.get(name=category_name)
    products = category.products.all()
    categories = Category.objects.all()
    
    paginator = Paginator(products, 5)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    
    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    
    return render(request, 'giftweb/products_by_category.html', context)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'giftweb/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()

        # Add some debugging output
        print("Product ID:", product.id)
        reviews = Review.objects.filter(product=product)
        print("Number of Reviews:", reviews.count())

        # Retrieve reviews for the product using the appropriate field (e.g., 'product' if that's the field name)
        reviews = Review.objects.filter(product=product)

        if product.discount:
            discounted_price = product.price - product.discount
            context['discounted_price'] = discounted_price

        # Retrieve the features associated with the product
        features = product.features.all()  # Assuming 'features' is the related name for the ManyToManyField

        context['categories'] = Category.objects.all()
        context['reviews'] = reviews
        context['features'] = features  # Pass the features to the template

        return context




from django.db.models import Q

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def home(request):
    search_query = request.GET.get('q', '')

    if search_query:
        products = Product.objects.filter(
            Q(name__icontains=search_query) |
            Q(features__name__icontains=search_query) |
            Q(categories__name__icontains=search_query)
        ).distinct()
        product_count = products.count()
    else:
        products = Product.objects.all()
        product_count = 0  # No need to count when not searching

    categories = Category.objects.all()

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
        my_recs = profile.get_recommended_profiles()

    for product in products:
        if product.discount:
            discounted_price = product.price - (product.price * product.discount / 100)
            product.discounted_price = discounted_price

    current_time = timezone.now()

    # Pagination
    paginator = Paginator(products, 7)  # Show 7 products per page
    page = request.GET.get('page')
    
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'categories': categories,
        'products': products,
        'search_query': search_query,
        'product_count': product_count,
        'paginator': paginator,
    }

    if request.user.is_authenticated:
        context['my_recs'] = my_recs

    return render(request, 'giftweb/index.html', context)


from django.shortcuts import redirect

@login_required
def payment_success(request):
    payment = Payment.objects.filter(user=request.user).order_by('-id').first()

    return render(request, 'giftweb/payment_success.html', {'payment': payment})



def policy(request):
    terms = Terms.objects.all()

    
    context = {
        'terms': terms
    }
    return render(request, 'giftweb/policy.html', context)


    
def documents_by_category(request, category_name):
    category = Category.objects.get(name=category_name)
    documents = category.products.all()
    categories = Category.objects.all()
    
    paginator = Paginator(documents, 5)
    page = request.GET.get('page')
    documents = paginator.get_page(page)
    
    context = {
        'category': category,
        'categories': categories,
        'documents': documents
    }
    
    return render(request, 'giftweb/documents_by_category.html', context)

    


class DocumentDetailView(DetailView):
    model = Document
    template_name = 'giftweb/document_detail.html'
    context_object_name = 'document'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        document = self.get_object()

        context['categories'] = Category.objects.all()

        return context

def documentHome(request):
    documents = Document.objects.all()

    context = {
        'documents': documents
    }

    return render(request, 'giftweb/document_list.html', context)


class BusinessView(DetailView):
    model = BusinessEmail
    template_name = 'giftweb/business_detail.html'
    context_object_name = 'business'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        business = self.get_object()

        # Add any additional context data you want to pass to the template here

        return context

def businessHome(request):
    business = BusinessEmail.objects.all()

    context = {
        'business': business
    }

    return render(request, 'giftweb/business_list.html', context)



def premium_home(request):
    products = PremiumProduct.objects.all()

    current_time = timezone.now()
    for product in products:

        if product.discount:
            discounted_price = product.price - (product.price * product.discount / 100)
            product.discounted_price = discounted_price

    return render(request, 'giftweb/products.html', {'products': products})


def about(request):
    return render(request, 'giftweb/about.html')

def blog_list(request):
    blogs = Blog.objects.all()
    return render(request, 'core/index.html', {'blogs': blogs})

def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        subject = request.POST['subject']
        email = request.POST['email']

giftweb/templates/giftweb/business_detail.html

{% extends 'core/base.html' %}



{% block content %}
{% load static %}
{% include "core/messages.html" %}



<div style="padding-top: 11px;" class="page-wrapper">
    <div class="content">
        <div class="page-header">
            <div class="page-title">
                <h4>Details</h4>
                <h6>Full details of {{ business.title|title }}</h6>
            </div>
            <a href="{% url 'giftweb:contact' %}" class="btn btn-added"><img src="{% static 'assetss/img/icons/plus.svg' %}" alt="img" class="me-1" />Contact Us</a>
        </div>
        <div class="page-btn"></div>
        <div class="row">
            <div class="col-lg-8 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="productdetails">
                            <ul class="product-bar">
                                <li>
                                    <h4>Name</h4>
                                    <h6>{{ business.email_address|title }}</h6>
                                </li>
                                <li>
                                    <h4>Type</h4>
                                    <h6>{{ business.type|title }} Mail</h6>
                                </li>
                                <li>
                                    <h4>Category</h4>
                                    <h6>{{ business.category|title }}</h6>
                                </li>
                                <li>
                                    <h4>Status</h4>
                                    <h6>Active</h6>
                                </li>
                                <li></li>
                            </ul>
                        </div>
                    </div>
                    <div class="product-description">
                        <h4>Description</h4>
                        <div class="description-content">
                            {{ business.description|safe }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="slider-product-details">
                            <div class="gallery-container">
                                <div class="image-grid">
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image3.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image4.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image5.url }}" id="__SYS_ProfilePhoto" />
                                    </div>

                                    <!-- Repeat this user-photo block for additional images -->
                                </div>
                            </div>
                            <button class="scroll-button scroll-left-button">&#9664; Click to Scroll</button>
                            <button class="scroll-button scroll-right-button">Click to Scroll &#9654;</button>
                            <button class="view-fullscreen-button">View Full Screen</button>
                            <!-- Add this button -->
                        </div>
                    </div>
                </div>
            </div>

            <!-- Add a modal dialog for full-screen gallery -->
            <div class="modal" id="fullscreen-modal">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Full-Screen Gallery</h5>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <div class="gallery-container">
                                <div class="image-grid-fullscreen">
                                    <!-- Populate this with the same images as the original gallery -->
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image2.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image3.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image4.url }}" id="__SYS_ProfilePhoto" />
                                    </div>
                                    <div class="user-photo">
                                        <img style="max-width: 150px; max-height: 130px;" src="{{ business.image5.url }}" id="__SYS_ProfilePhoto" />
                                    </div>

                                    <!-- Repeat this user-photo block for additional images -->
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <br />

            <div class="page-header">
                <div class="page-title">
                    <h4>Send A Message Through The Live Chat Support</h4>
                    <h6>Or</h6>
                </div>
                <a href="{% url 'giftweb:contact' %}" class="btn btn-added"><img src="{% static 'assetss/img/icons/plus.svg' %}" alt="img" class="me-1" />Contact Us Now</a>
            </div>
            <style>
                /* Add styles for the full-screen modal */
                .modal-xl {
                    /* Increase the modal size here */
                    max-width: 95%; /* Adjust the maximum width as needed */
                }

                .image-grid-fullscreen {
                    display: flex;
                    justify-content: flex-start;
                    align-items: center;
                    overflow-x: auto;
                    scroll-behavior: smooth;
                }
            </style>
            <style>
                .gallery-container {
                    position: relative;
                    width: 100%;
                    overflow: hidden;
                    white-space: nowrap;
                }

                .image-grid {
                    display: flex;
                    justify-content: flex-start;
                    align-items: center;
                    overflow-x: auto;
                    scroll-behavior: smooth; /* Add smooth scrolling behavior */
                }

                .user-photo {
                    margin-right: 20px;
                }

                .scroll-button {
                    background-color: rgba(255, 255, 255, 0.8);
                    padding: 5px;
                    cursor: pointer;
                    z-index: 1;
                }

                .scroll-left-button {
                    margin-right: 10px; /* Add some spacing between buttons */
                }

                .scroll-right-button {
                    margin-left: 10px; /* Add some spacing between buttons */
                }
            </style>

            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    const scrollLeftButton = document.querySelector('.scroll-left-button');
                    const scrollRightButton = document.querySelector('.scroll-right-button');
                    const imageGrid = document.querySelector('.image-grid');
                    const viewFullscreenButton = document.querySelector('.view-fullscreen-button');
                    const fullscreenModal = document.getElementById('fullscreen-modal');

                    scrollLeftButton.addEventListener('click', () => {
                        imageGrid.scrollBy({
                            left: -150,
                            behavior: 'smooth',
                        });
                    });

                    scrollRightButton.addEventListener('click', () => {
                        imageGrid.scrollBy({
                            left: 150,
                            behavior: 'smooth',
                        });
                    });

                    viewFullscreenButton.addEventListener('click', () => {
                        // Show the full-screen modal
                        fullscreenModal.style.display = 'block';
                    });

                    // Close the full-screen modal when the close button or the modal footer button is clicked
                    const closeModalButton = document.querySelector('.modal .close');
                    closeModalButton.addEventListener('click', () => {
                        fullscreenModal.style.display = 'none';
                    });

                    const modalFooterCloseButton = document.querySelector('.modal-footer button');
                    modalFooterCloseButton.addEventListener('click', () => {
                        fullscreenModal.style.display = 'none';
                    });
                });
            </script>
            <script>
                // Wait for the page to finish loading
                window.addEventListener("load", function () {
                    // Find the global-loader div
                    var globalLoader = document.getElementById("global-loader");

                    // Display the loader for 2 seconds, then hide it
                    setTimeout(function () {
                        globalLoader.style.display = "none";
                    }, 1000); // 2000 milliseconds (2 seconds)
                });
            </script>

            <div class="for-editor">
                {% for category in product.categories.all %} {% if not forloop.last %}, {% endif %}

                <br />
                <a href="{% url 'giftweb:products_by_category' category_name=category.name %}">More profiles from {{ category.name }}{% if not forloop.last %}, {% endif %} {% endfor %} </a>
            </div>
        </div>
    </div>
</div>




    <script src="{% static 'assetss/js/feather.min.js' %}"></script>

    <script src="{% static 'assetss/js/jquery.slimscroll.min.js' %}"></script>


    <script src="{% static 'assetss/plugins/owlcarousel/owl.carousel.min.js' %}"></script>

    <script src="{% static 'assetss/plugins/select2/js/select2.min.js' %}"></script>

    <script src="{% static 'assetss/js/script.js' %}"></script>
{% endblock %}

giftweb/templates/giftweb/policy.html
{% extends 'core/base.html' %}

{% block content %}
{% load static %}
{% load random_filters %}

{% include "core/messages.html" %}



    <body>


        <div style="padding-top: 46px;" class="page-wrapper cardhead">
            <div class="content">

                <div class="page-header">
                    <div class="row">
                        <div class="col-sm-12">
                            <h3 class="page-title">Acceptable Use Policy (AUP):</h3>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="">Terms of Service (TOS) or Terms and Conditions:</a></li>
                                <li class="breadcrumb-item active">Privacy Policy</li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row">

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title"></h5>
        </div>
        <div style="padding-top: 4px;" class="card-body">
            {% for term in terms %}
                <div class="clipboard copy-txt">
                    <p class="otp-pass">{{ term.name }}</p>
                    <p class="mb-4">{{ term.conditions|safe }}</p>
                    <a class="mb-1 btn clip-btn btn-primary" href="{% url 'giftweb:contact' %}"><i data-feather="pen-tool"></i> Contact Us </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>


                </div>
            </div>
        </div>



    </body>
{% endblock %}